###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: Europe/Brussels
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages

###################################################
#                                                 #
#                     Panel                       #
#                                                 #
###################################################

panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret grafana_url

  nodered:
    title: Node-Red
    icon:  mdi:shuffle-variant
    url: !secret nodered_url

###################################################
#                                                 #
#                     Influx Database             #
#                                                 #
###################################################

influxdb:
  host: !secret influx_host
  port: !secret influx_port
  database: !secret influx_db
  username: !secret influx_user
  password: !secret influx_passsword
  max_retries: 3
  default_measurement: state

####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################

mqtt:
  broker: core-mosquitto
  username: !secret mozzieuser
  password: !secret mozziepass

frontend:

http:
  api_password: !secret http_password

config:
updater:
discovery:
conversation:

# history:
# logbook:
# map:
# cloud:

####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################

group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
zone: !include includes/zones.yaml
media_player: !include includes/media_players.yaml
