###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

homeassistant:
  name: Home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  time_zone: UTC
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages

###################################################
#                                                 #
#                     Panel                       #
#                                                 #
###################################################

panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret grafana_url

  nodered:
    title: Node-Red
    icon: mdi:auto-fix
    url: !secret nodered_url

###################################################
#                                                 #
#                     Influx Database             #
#                                                 #
###################################################

influxdb:
  host: !secret influx_host
  port: !secret influx_port
  database: !secret influx_db
  username: !secret influx_user
  password: !secret influx_passsword
  max_retries: 3
  default_measurement: state

####################################################
#                                                  #
#                 Customizations                   #
#                                                  #
####################################################

frontend:

####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################

mqtt:
  broker: core-mosquitto
#   username: !secret mozzieuser
#   password: !secret mozziepass

config:
http:
updater:
discovery:
conversation:
# history:
# logbook:
map:
sun:

sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
# cloud:

####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################

group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
