#################################################################
#                                                               #
#                      Packages/Lighting                        #
#                                                               #
#################################################################

#################################################################
#                          Customize                            #
#################################################################

homeassistant:
  customize:
## Lights & Switches
    light.fibaro_kitchen_dimmer_level:
      friendly_name: "Kitchen Light"
      homebridge_visible: true
    light.fibaro_hallway_dimmer_level:
      friendly_name: "Hallway Light"
      homebridge_visible: true
    light.fibaro_stair_dimmer_level:
      friendly_name: "Stairway"
      homebridge_visible: true
    light.fibaro_table_dimmer_level:
      friendly_name: "Dining Light"
      homebridge_visible: true
    light.hue_lightstrip:
      friendly_name: "LED Strip"
      homebridge_visible: true
    light.hue_livingroom:
      friendly_name: "Guitar Lamp"
      homebridge_visible: true
    light.hue_desk:
      friendly_name: "Desk Light"
      homebridge_visible: true
    switch.wemo_livingroom:
      friendly_name: "TV Lights"
      homebridge_visible: true

#################################################################
#                           Group                               #
#################################################################

group:
  downstairs lights:
    name: Downstairs Lights
    view: no
    entities:
      - light.hue_desk
      - light.hue_lightstrip
      - light.hue_livingroom
      - switch.wemo_livingroom

  scene selection:
    name: Scene Selection
    view: no
    entities:
      - input_select.scene_selector

#################################################################
#                         Automations                           #
#################################################################

automation:
  - alias: Scene Selection
    trigger:
      platform: state
      entity_id: input_select.scene_selector
    action:
      service: scene.turn_on
      data_template:
        entity_id: scene.{{trigger.to_state.state}}
