####################################################
#                                                  #
#                      System                      #
#                                                  #
####################################################

# TODO: if enabled it gives a zeroconf error as this runs on live rPi
- action:
  - delay: 00:05  # Waits 5 minutes
  - service: script.1523505263098
  alias: Start Apple Homekit
  condition: []
  id: '1523506259174'
  trigger:
  - platform: homeassistant
    event: start
  initial_state: false # change here to enable
