####################################################
#                                                  #
#                    Time/Date                     #
#                                                  #
####################################################

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - time_date
      - time_utc
      - beat

####################################################
#                                                  #
#               Certificate Expiry                 #
#                                                  #
####################################################

- platform: cert_expiry
  host: dglerum.noip.me
