#################################################################
#                                                               #
#                      Packages/Firmware   OK                   #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    binary_sensor.ha_update_available:
      icon: mdi:cloud-download

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  firmware:
    name: Firmware Status
    view: no
    entities:
      - binary_sensor.ha_update_available
